env:
  global:
    - Features=use-mock-crust
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
branches:
  only:
    - master
    - stable
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly-2016-11-17
sudo: false
cache:
  cargo: true
before_script:
  - (which cargo-install-update && cargo install-update cargo-update) || cargo install cargo-update
  - (which rustfmt && cargo install-update rustfmt) || cargo install rustfmt
  - (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
  - if [ "${TRAVIS_RUST_VERSION}" = nightly-2016-11-17 ]; then
    (
      which cargo-clippy || cargo install clippy --vers=0.0.99
    );
    fi
script:
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        cargo fmt -- --write-mode=diff &&
        cargo rustc --verbose -- --test -Zno-trans &&
        cargo rustc --verbose --example ci_test -- -Zno-trans &&
        cargo rustc --verbose --example key_value_store -- -Zno-trans &&
        cargo rustc --verbose -- -Zno-trans &&
        cargo test  --verbose --features use-mock-crust
      );
    else
       cargo clippy;
    fi
before_cache:
  - cargo prune
