[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "https://docs.rs/routing/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.25.1"

[dependencies]
crust = "~0.19.0"
itertools = "~0.5.6"
log = "~0.3.6"
lru_time_cache = "~0.5.0"
maidsafe_utilities = "~0.10.0"
quick-error = "~1.1.0"
rand = "~0.3.14"
rust_sodium = "~0.1.2"
rustc-serialize = "~0.3.21"
term = "~0.4.4"
tiny-keccak = "~1.1.1"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.6.86"
libc = "~0.2.17"

[[example]]
bench = false
name = "key_value_store"
test = false

[[example]]
bench = false
name = "ci_test"
test = false

[features]
use-mock-crust = []
